### ISSUE TITLE
have a error when i run predict.py

### ISSUE THREAD

**Issue by lfydegithub** [Timen/squeezenext-tensorflow#5]
args:
`parser = argparse.ArgumentParser(description='Process some integers.')
parser.add_argument('image_path', type=str, default='tabby_cat.jpg',
                    help='Location of eval jpeg image')
parser.add_argument('--model_dir', type=str, default='./ckpt',
                    help='Location of model_dir')
parser.add_argument('--configuration', type=str, default="v_1_0_SqNxt_23_mod",
                    help='Name of model config file')
parser.add_argument('--imagenet_metadata_file', type=str, default="./datasets/imagenet_metadata.txt",
                    help='Path to metadata file')
parser.add_argument('--labels_file', type=str, default="./datasets/imagenet_lsvrc_2015_synsets.txt",
                    help='Path to labels file')
args = parser.parse_args()`

### error:
`  module = self._system_import(name, *args, **kwargs)
Traceback (most recent call last):
  File "/home/lfy/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-de9e0ed01528>", line 1, in <module>
    runfile('/home/lfy/work/squeezenext/squeezenext-tensorflow-master/predict.py', wdir='/home/lfy/work/squeezenext/squeezenext-tensorflow-master')
  File "/opt/pycharm-2018.3.4/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/opt/pycharm-2018.3.4/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/lfy/work/squeezenext/squeezenext-tensorflow-master/predict.py", line 3, in <module>
    from configs import configs
  File "/opt/pycharm-2018.3.4/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/lfy/work/squeezenext/squeezenext-tensorflow-master/configs/__init__.py", line 6, in <module>
    configs[module[:-3]] = __import__(module[:-3], locals(), globals()).training_params
  File "/opt/pycharm-2018.3.4/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'v_1_0_SqNxt_23_v5'`

**Comment by tijmen-loomai** [comment]
Are you running the code using python 2.7?
